[package]
name = "library"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"] }

front_matter = { path = "../front_matter" }
config = { path = "../config" }
utils = { path = "../utils" }
rendering = { path = "../rendering" }
errors = { path = "../errors" }
libs = { path = "../libs" }

[dev-dependencies]
tempfile = "3"
