[package]
name = "config"
version = "0.1.0"
edition = "2021"
include = ["src/**/*"]

[dependencies]
serde = {version = "1.0", features = ["derive"] }
# TODO: remove me if we can get highlight to work with once_cell
lazy_static = "1"

errors = { path = "../errors" }
utils = { path = "../utils" }
libs = { path = "../libs" }
