[package]
name = "site"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"
include = ["src/**/*"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
templates = { path = "../templates" }
front_matter = { path = "../front_matter" }
search = { path = "../search" }
imageproc = { path = "../imageproc" }
library = { path = "../library" }
link_checker = { path = "../link_checker" }
libs = { path = "../libs" }

[dev-dependencies]
tempfile = "3"
path-slash = "0.1.4"
