[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = "../errors" }
library = { path = "../library" }
config = { path = "../config" }
libs = { path = "../libs" }
