[package]
name = "templates"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"] }

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }
rendering = { path = "../rendering" }
libs = { path = "../libs" }


[dev-dependencies]
mockito = "0.30"
tempfile = "3"
